### ISSUE TITLE
DistributionNotFound: The 'psycopg2' distribution was not found and is required by osmtm

### ISSUE THREAD

**Issue by baditaflorin** [hotosm/osm-tasking-manager2#668]
i had installed psycopg2 via sudo pip install psycopg2
If i try to install again i will get : 
sudo pip install psycopg2
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /usr/local/lib/python2.7/dist-packages
Cleaning up...

the error that i get
./env/bin/initialize_osmtm_db
Traceback (most recent call last):
  File "./env/bin/initialize_osmtm_db", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/data/files/florinb/osm_tasking_manager/osm-tasking-manager2/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'psycopg2' distribution was not found and is required by osmtm

**Comment by pgiraud** [comment]
`psycopg2` needs to be installed in the virtualenv.
Using `sudo pip install psycopg2` you're installing in the system environment.

Try the following command instead:
```
./env/bin/pip install psycopg2
```

**Comment by baditaflorin** [comment]
@pgiraud thank you, this worked perfect :)
