### ISSUE TITLE
Installation problem: nose version conflict

### ISSUE THREAD

**Issue by iandees** [hotosm/osm-tasking-manager2#679]
I'm trying to install OSMTM2 on Ubuntu 12.04.5 LTS. I created a brand new virtualenv and installed the requirements:

``` bash
osm-tasking-manager2$ rm -rf venv/
iandees@benzene:/var/www/tasks.openstreetmap.us/osm-tasking-manager2$ virtualenv --no-site-packages venv
New python executable in venv/bin/python
Installing setuptools............done.
Installing pip...............done.
iandees@benzene:/var/www/tasks.openstreetmap.us/osm-tasking-manager2$ ./venv/bin/pip install -r requirements.txt
```

...everything goes great up until it tries to install nose:

```
  Running setup.py install for simplejson
    building 'simplejson._speedups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c simplejson/_speedups.c -o build/te
mp.linux-x86_64-2.7/simplejson/_speedups.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/simplejson/_speedups.o -o build/
lib.linux-x86_64-2.7/simplejson/_speedups.so

  Running setup.py install for geojson
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/geojson/setup.py", line 44, in <module>
        "Topic :: Scientific/Engineering :: GIS",
      File "/usr/lib/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 260, in __init__
      File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 284, in fetch_build_eggs
      File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 569, in resolve
    pkg_resources.VersionConflict: (nose 1.3.7 (/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/lib/python2.7/site-packages), Requirement.parse('nose==1.3.0'))
    Complete output from command /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/bin/python -c "import setuptools;__file__='/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/geojson/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-flRzCt-record/install-record.txt --single-version-externally-managed --install-headers /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/geojson/setup.py", line 44, in <module>

    "Topic :: Scientific/Engineering :: GIS",

  File "/usr/lib/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 260, in __init__

  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/setuptools/dist.py", line 284, in fetch_build_eggs

  File "/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 569, in resolve

pkg_resources.VersionConflict: (nose 1.3.7 (/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/lib/python2.7/site-packages), Requirement.parse('nose==1.3.0'))

----------------------------------------
Command /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/bin/python -c "import setuptools;__file__='/var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/geojson/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-flRzCt-record/install-record.txt --single-version-externally-managed --install-headers /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/include/site/python2.7 failed with error code 1 in /var/www/tasks.openstreetmap.us/osm-tasking-manager2/venv/build/geojson
```

**Comment by pgiraud** [comment]
I've been able to reproduce the issue yet. I'll try on my ubuntu box at the office tomorrow.
I wonder if using a more recent version of geojson would help.

**Comment by iandees** [comment]
That did it. I changed the `geojson` dependency to `1.3.0` and deleted the virtualenv, recreated, and reinstalled.

**Comment by bgirardot** [comment]
This sounds fixed! Please let me know if it is not
