### ISSUE TITLE
Error while running script ./env/bin/initialize_osmtm_db

### ISSUE THREAD

**Issue by deepbasu007** [hotosm/osm-tasking-manager2#763]
While trying to install the OSM Task Manager, I followed all the steps mentioned in the wiki. However, while trying to initialize the database using the script provided in the wiki,
./env/bin/initialize_osmtm_db

I got the error:

sqlalchemy.exc.ProgrammingError: (ProgrammingError) permission denied for relation spatial_ref_sys

CONTEXT:  SQL statement "SELECT proj4text FROM spatial_ref_sys WHERE srid = 4326 LIMIT 1"

 'SELECT ST_AsBinary(ST_Transform(ST_SetSRID(ST_Multi(ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s)), %(param_1)s), %(param_2)s)) AS "ST_Transform_1"' {'ST_GeomFromWKB_1': <read-only buffer for 0x2f2e690, size -1, offset 0 at 0x2f36fb0>, 'param_2': 3857, 'param_1': 4326, 'ST_GeomFromWKB_2': 4326}

A detailed error log:

Traceback (most recent call last):
  File "./env/bin/initialize_osmtm_db", line 9, in <module>
    load_entry_point('osmtm', 'console_scripts', 'initialize_osmtm_db')()
  File "/data/users/saikatbasu/osm-tasking-manager2/osmtm/scripts/initializedb.py", line 107, in main
    project.auto_fill(17)
  File "/data/users/saikatbasu/osm-tasking-manager2/osmtm/models.py", line 502, in auto_fill
    geom_3857 = DBSession.execute(ST_Transform(self.area.geometry, 3857)) \
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1021, in execute
    bind, close_with_result=True).execute(clause, params or {})
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/sql/functions.py", line 66, in _execute_on_connection
    return connection._execute_function(self, multiparams, params)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 847, in _execute_function
    multiparams, params)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1070, in _execute_context
    context)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1063, in _execute_context
    context)
  File "/data/users/saikatbasu/osm-tasking-manager2/env/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) permission denied for relation spatial_ref_sys
CONTEXT:  SQL statement "SELECT proj4text FROM spatial_ref_sys WHERE srid = 4326 LIMIT 1"
 'SELECT ST_AsBinary(ST_Transform(ST_SetSRID(ST_Multi(ST_GeomFromWKB(%(ST_GeomFromWKB_1)s, %(ST_GeomFromWKB_2)s)), %(param_1)s), %(param_2)s)) AS "ST_Transform_1"' {'ST_GeomFromWKB_1': <read-only buffer for 0x2f2e690, size -1, offset 0 at 0x2f36fb0>, 'param_2': 3857, 'param_1': 4326, 'ST_GeomFromWKB_2': 4326}

Can anyone please help me figure out the problem? Thanks.

**Comment by ethan-nelson** [comment]
Hmmm what are the permissions for the database user you created? Are they the owner of the database?

**Comment by deepbasu007** [comment]
Solved it! Actually there was some permission issues with www-data user and the postgres user. I created a new user and granted all permissions to that user. And bingo!

**Comment by ethan-nelson** [comment]
Great! Closing ticket.
