### ISSUE TITLE
./env/bin/initialize_osmtm_db returns error

### ISSUE THREAD

**Issue by fazlerabbi37** [hotosm/osm-tasking-manager2#998]
OS: Ubuntu 16.04 
I was following Debian installation form Wiki. Upon giving ./env/bin/initialize_osmtm_db I got the following errors:
Traceback (most recent call last):
  File "./env/bin/initialize_osmtm_db", line 11, in <module>
    load_entry_point('osmtm', 'console_scripts', 'initialize_osmtm_db')()
  File "/home/user/osm-tasking-manager2/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/osm-tasking-manager2/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/user/osm-tasking-manager2/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/user/osm-tasking-manager2/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/user/osm-tasking-manager2/osmtm/__init__.py", line 11, in <module>
    from .models import (
  File "/home/user/osm-tasking-manager2/osmtm/models.py", line 56, in <module>
    from .utils import (
  File "/home/user/osm-tasking-manager2/osmtm/utils.py", line 2, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

Can anybody please help me resolve this?

**Comment by pgiraud** [comment]
Just in case, what version of python are you using?

**Comment by fazlerabbi37** [comment]
@pgiraud Python  version 3.5.2

**Comment by pgiraud** [comment]
Could you try using python 2.x? I don't think TM2 can work with python 3.x unfortunately. You should be able to choose which version to use when initializing the virtual env.

**Comment by fazlerabbi37** [comment]
thanks! solved it with the following command:
`virtualenv --python=/usr/bin/python2.7  --no-site-packages env`
